# Generated by Django 3.1 on 2020-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('last_date', models.DateField()),
            ],
        ),
    ]
